
theme: jekyll-theme-minimal
title: Agustín Farías Lobo
description: Hi. I am Agustín Farías Lobo, an economics student at Universidad de Chile. You can read my CV here.\n This page was created to upload all of my work as a student and as an economist (I hope). Here you will find some notes on Macroeconomics, Microeconomics and Econometrics related to courses I took during my time at Universidad de Chile.


